language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
deploy:
  provider: releases
  api_key:
    secure: p+zdOm03/9BqN1MhmZeQvUcX/SgAFHz8E2lYCxuVYxZK7Fpu0PGXW3kPOTdv3EgNRYuEs0X0xYknKM5p8XAC3NZYYurMQESqPAVz0FooKVcvaJV5ZwG2O3kssSR4TPrxx5zC94PASnZA049f7an6RLRT2i2Mne26SaG3U1KHM5QT/wm3Juys0zCh7hkD7ygDNtpk7LuBtqZJbhY/1n//YUzzic424C/B7wWZIrl7j1dQphmTiMsTM5uXbWwQPtAS+0j1nvtbOoFrpcL2QJZRxmFJ+x8iQP+ZZmnd5UB3gxGLJ5PFtuxn6q9KEHUwl9/pMALoN9oX5o/+Ibp9vL3LidoDOn0DJaeCGDp+ypzMTbKPUdoZnCVQZtOOv6vop9adX+DzAOzbGzqLk7u65gNxkq3oVgf4h9/FJOWrHZBsoDX30iZkC2/8KMCHR14PTxHB2lloHWaB78eRJvJ7bMfcTzGXdN0AlZG59rnQDWUZADJZuqrYEJsZ5+ur+wv57ST+2i0PAeTKzj3FkZyjJuHxSyU/O1kCd9MQxQcyZ7Zh2BALble1pIUSnDRzjpjrrbcWQXphvfpztzwK8WbhaEa6th2W1/JMoVIuaEfLoMKny0CJhO9Ox7rylEJwTp08Er73v+1Rj4gE0Wxs5WUSSs3Apis00TORiXlQ2kmnmngFEMU=
  file: target/ir-sexp-parser-java-1.0-SNAPSHOT.jar
  skip_cleanup: true
  on:
    tags: true
